/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import businessLayer.TaiKhoanBL;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author mhuy2
 */
public class FrmMain extends javax.swing.JFrame {
int hour,second,minute;
int day,month,year;
String strtime,stryear;
    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuDangXuat = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuThoat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuNV = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuKH = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuBD = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuPhim = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        mnuThongTinBaiHat = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem12 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần mềm quản lý cửa hàng băng đĩa");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("QUẢN LÝ CỬA HÀNG BĂNG ĐĨA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 320, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hello.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 80, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundBD.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 420));

        jMenuBar1.setBackground(new java.awt.Color(204, 0, 204));
        jMenuBar1.setBorder(null);
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hethong.png"))); // NOI18N
        jMenu1.setText("Hệ thống");
        jMenu1.setPreferredSize(new java.awt.Dimension(100, 30));

        mnuDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        mnuDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        mnuDangXuat.setText("Đăng xuất");
        mnuDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(mnuDangXuat);
        jMenu1.add(jSeparator3);

        mnuThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        mnuThoat.setText("Thoát");
        mnuThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuThoatActionPerformed(evt);
            }
        });
        jMenu1.add(mnuThoat);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/QuanLy.png"))); // NOI18N
        jMenu2.setText("Quản lý");
        jMenu2.setPreferredSize(new java.awt.Dimension(100, 20));

        mnuNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nhanvien.png"))); // NOI18N
        mnuNV.setText("Nhân viên");
        mnuNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNVActionPerformed(evt);
            }
        });
        jMenu2.add(mnuNV);
        jMenu2.add(jSeparator1);

        mnuKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/khachhang.png"))); // NOI18N
        mnuKH.setText("Khách hàng");
        mnuKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKHActionPerformed(evt);
            }
        });
        jMenu2.add(mnuKH);
        jMenu2.add(jSeparator2);

        mnuBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BangDia.png"))); // NOI18N
        mnuBD.setText("Băng đĩa");
        mnuBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBDActionPerformed(evt);
            }
        });
        jMenu2.add(mnuBD);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PhieuThue.png"))); // NOI18N
        jMenu3.setText("Quản lý phiếu");
        jMenu3.setPreferredSize(new java.awt.Dimension(120, 19));

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/phieu.png"))); // NOI18N
        jMenuItem6.setText("Phiếu thuê");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);
        jMenu3.add(jSeparator4);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PhieuPhat.png"))); // NOI18N
        jMenuItem3.setText("Phiếu phạt");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tradia (1).png"))); // NOI18N
        jMenu7.setText("Trả băng đĩa");
        jMenu7.setPreferredSize(new java.awt.Dimension(110, 19));

        jMenuItem2.setText("Trả băng đĩa");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem2);

        jMenuBar1.add(jMenu7);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tracuu.png"))); // NOI18N
        jMenu4.setText("Tìm kiếm");
        jMenu4.setPreferredSize(new java.awt.Dimension(100, 19));

        mnuPhim.setText("Thông tin phim");
        mnuPhim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPhimActionPerformed(evt);
            }
        });
        jMenu4.add(mnuPhim);
        jMenu4.add(jSeparator8);

        mnuThongTinBaiHat.setText("Thông tin bài hát");
        mnuThongTinBaiHat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuThongTinBaiHatActionPerformed(evt);
            }
        });
        jMenu4.add(mnuThongTinBaiHat);
        jMenu4.add(jSeparator11);

        jMenuItem1.setText("Mã phiếu thuê");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/thongke.png"))); // NOI18N
        jMenu5.setText("Thống kê các khách hàng được thưởng ");

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lich.png"))); // NOI18N
        jMenuItem11.setText("Theo tháng");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);
        jMenu5.add(jSeparator7);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lich.png"))); // NOI18N
        jMenuItem12.setText("Theo năm");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem12);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKHActionPerformed
        FrmQuanLyKhachHang kh=new FrmQuanLyKhachHang();
        kh.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuKHActionPerformed

    private void mnuDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDangXuatActionPerformed
        int tb= JOptionPane.showConfirmDialog(this, "Bạn muốn đăng xuất không ?","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(tb==JOptionPane.YES_OPTION)
        {
            FrmDangNhap log= new FrmDangNhap();
            log.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_mnuDangXuatActionPerformed

    private void mnuThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuThoatActionPerformed
       int tb=JOptionPane.showConfirmDialog(this, "Bạn muốn thoát chương trình ?","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(tb==JOptionPane.YES_OPTION)
        System.exit(0);
    }//GEN-LAST:event_mnuThoatActionPerformed

    private void mnuNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNVActionPerformed
        FrmQuanLyNhanVien nv=new FrmQuanLyNhanVien();
        nv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuNVActionPerformed

    private void mnuBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBDActionPerformed
         FrmQuanLyBangDia bd=new FrmQuanLyBangDia();
        bd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuBDActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
     FrmPhieuThue bd=new FrmPhieuThue();
        bd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void mnuThongTinBaiHatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuThongTinBaiHatActionPerformed
    FrmTimKiemThongTinBaiHat ttBaiHat=new FrmTimKiemThongTinBaiHat();
    ttBaiHat.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_mnuThongTinBaiHatActionPerformed

    private void mnuPhimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPhimActionPerformed
         FrmTimKiemThongTinPhim tt=new FrmTimKiemThongTinPhim();
    tt.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_mnuPhimActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmTimKiemMaPhieuThue frmTimKiemMaPhieuThue=new FrmTimKiemMaPhieuThue();
        frmTimKiemMaPhieuThue.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmTraBangDia traBangDia=new FrmTraBangDia();
        traBangDia.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        FrmPhieuPhat phieuPhat=new FrmPhieuPhat();
        phieuPhat.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        FrmThongKeTheoThang frmThongKeTheoThang=new FrmThongKeTheoThang()   ;
        frmThongKeTheoThang.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        FrmThongKeTheoNam frmThongKeTheoNam=new FrmThongKeTheoNam();
        frmThongKeTheoNam.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JMenuItem mnuBD;
    private javax.swing.JMenuItem mnuDangXuat;
    private javax.swing.JMenuItem mnuKH;
    private javax.swing.JMenuItem mnuNV;
    private javax.swing.JMenuItem mnuPhim;
    private javax.swing.JMenuItem mnuThoat;
    private javax.swing.JMenuItem mnuThongTinBaiHat;
    // End of variables declaration//GEN-END:variables

    
   
}
