/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import businessLayer.ChiTietPhieuThueBL;
import businessLayer.KhachHangBL;
import businessLayer.NhanVienBL;
import businessLayer.PhieuThueBL;
import dataTransferObject.ChiTietPhieuThue;
import dataTransferObject.KhachHang;
import dataTransferObject.NhanVien;
import dataTransferObject.PhieuThue;
import java.sql.Date;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mhuy2
 */
public class FrmPhieuThue extends javax.swing.JFrame {

    /**
     * Creates new form FrmQuanLyPhieuThue
     */
    public FrmPhieuThue() {
        initComponents();
        initPhieuThue();
        initMaNV();
       initMaKH();
    }
     DefaultTableModel model;
    void initPhieuThue()
    {
        List<PhieuThue> listHD;
       listHD=PhieuThueBL.dsPhieuThue();
        if(listHD.size()>0)
        {
            model=(DefaultTableModel)tblPT.getModel();
            for(PhieuThue hd:listHD)
            {
               
                model.addRow(new Object[]{hd.getStrMaPT(),hd.getStrMaNV(),hd.getdNgayThue(),hd.getStrMaKH(),hd.getIntThoiHan(),hd.getDbTongTien()});
               
            }
    }
}
void initMaNV()
{
    List<NhanVien>listNV;
    listNV=NhanVienBL.dsNhanVien();
    if(listNV.size()>0)
    {
        for(NhanVien a:listNV)
        {
            cboMaNV.addItem(String.valueOf(a.getStrMaNV()));
        }
    }
}
private void initTenNV()
{
    List<PhieuThue>listNV;
   String manv=cboMaNV.getSelectedItem().toString();
    listNV=PhieuThueBL.HienThiTenNV(manv);
    if(listNV.size()>0)
    {
       
        for(PhieuThue nv:listNV)
        {
           
            txtTenNV.setText(nv.getStrTenNV());
        }
    }
}
void initMaKH()
{
    List<KhachHang>listKH;
    listKH=KhachHangBL.dsKhachHang();
    if(listKH.size()>0)
    {
        for(KhachHang a:listKH)
        {
            cboMaKH.addItem(String.valueOf(a.getStrMaKH()));
        }
    }
}
private void initTenKH()
{
    List<PhieuThue>listKH;
   String ma=cboMaKH.getSelectedItem().toString();
    listKH=PhieuThueBL.HienThiTenKH(ma);
    if(listKH.size()>0)
    {
       
        for(PhieuThue kh:listKH)
        {
           
            txtTenKH.setText(kh.getStrTenKH());
        }
    }
}
void ResetAll()
{
    txtMaPT.setEnabled(true);
    txtMaPT.setText("");
    cboMaNV.setSelectedItem("------Chọn--------");
    txtNgayThue.setText("");
     cboMaKH.setSelectedItem("------Chọn--------");
    txtThoiHan.setText("");
    txtTongTien.setText("0");
    tblPT.clearSelection();
    btnXoa.setEnabled(false);
    btnSua.setEnabled(false);
    btnLuu.setEnabled(true);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPT = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        txtMaPT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cboMaNV = new javax.swing.JComboBox<>();
        cboMaKH = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        txtTenNV = new javax.swing.JTextField();
        txtNgayThue = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtThoiHan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnCTPT = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phiếu thuê");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu thuê", "Mã nhân viên", "Ngày thuê", "Mã khách hàng", "Thời hạn trả", "Tổng tiền"
            }
        ));
        tblPT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPT);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 670, 150));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin phiếu thuê", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 51, 153))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Mã phiếu thuê:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 17, -1, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Tên nhân viên:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Ngày thuê:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Mã khách hàng:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, 30));

        txtTenKH.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtTenKH.setEnabled(false);
        txtTenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKHActionPerformed(evt);
            }
        });
        jPanel3.add(txtTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 180, 30));

        txtMaPT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel3.add(txtMaPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 180, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Tên khách hàng:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, 30));

        cboMaNV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cboMaNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------Chọn--------" }));
        cboMaNV.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMaNVItemStateChanged(evt);
            }
        });
        cboMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaNVActionPerformed(evt);
            }
        });
        jPanel3.add(cboMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 180, 30));

        cboMaKH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cboMaKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------Chọn--------" }));
        cboMaKH.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMaKHItemStateChanged(evt);
            }
        });
        cboMaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaKHActionPerformed(evt);
            }
        });
        jPanel3.add(cboMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 180, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Mã nhân viên:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 30));

        txtTongTien.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtTongTien.setText("0");
        txtTongTien.setEnabled(false);
        jPanel3.add(txtTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 180, 30));

        txtTenNV.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtTenNV.setEnabled(false);
        jPanel3.add(txtTenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 180, 30));

        txtNgayThue.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel3.add(txtNgayThue, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 180, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Ngày");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, 30));

        txtThoiHan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel3.add(txtThoiHan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 110, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 0, 51));
        jLabel13.setText("Tổng tiền sẽ được tính sau khi tính tiền trong chi tiết phiếu thuê");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 410, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Tổng tiền");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 140, 60, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Thời hạn trả:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 670, 220));

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 110, -1));

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add-icon .png"))); // NOI18N
        btnThem.setText("Làm mới");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 110, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("PHIẾU THUÊ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modify.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 110, -1));

        btnLuu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sua.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        getContentPane().add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 110, -1));

        btnCTPT.setBackground(new java.awt.Color(204, 204, 255));
        btnCTPT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCTPT.setText("Xem chi tiêt phiếu thuê");
        btnCTPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTPTActionPerformed(evt);
            }
        });
        getContentPane().add(btnCTPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 280, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 110, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 51));
        jLabel7.setText("Click vào 1 dòng sau đó ấn xem chi tiết phiếu thuê");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 340, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background .jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaNVActionPerformed
    if(cboMaNV.getSelectedItem().equals("------Chọn--------"))
        {
            txtTenNV.setText("");
        }        
    }//GEN-LAST:event_cboMaNVActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        FrmMain all=new FrmMain();
        all.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
     String NgayTh=txtNgayThue.getText();
        
      
        
       if(cboMaNV.getSelectedItem().equals("------Chọn--------"))
        {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn mã nhân viên !","Thông báo",JOptionPane.WARNING_MESSAGE);
            cboMaNV.requestFocus();   
        }
         else if(txtNgayThue.getText().equals(""))
        {
           JOptionPane.showMessageDialog(this, "Vui lòng nhập ngày thuê! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtNgayThue.requestFocus();
        }
        else if(!NgayTh.matches("^\\d{4}\\-(0[1-9]|1[012])\\-(0[1-9]|[12][0-9]|3[01])$"))
        {
           JOptionPane.showMessageDialog(rootPane,"'"+txtNgayThue.getText()+"'"+" không đúng định định dạng ngày thuê.\nPhải nhập đúng định dạng yyyy-MM-dd","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtNgayThue.requestFocus();  
        }
        else if(cboMaKH.getSelectedItem().equals("------Chọn--------"))
        {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn mã khách hàng !","Thông báo",JOptionPane.WARNING_MESSAGE);
            cboMaKH.requestFocus();   
        }
        else if(txtThoiHan.getText().equals(""))
        {
           JOptionPane.showMessageDialog(this, "Vui lòng nhập thời trả! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtThoiHan.requestFocus();
        }
       
        else
        {
        String MaPT=txtMaPT.getText();
        String MaNV=cboMaNV.getSelectedItem().toString();
        Date NgayThue=Date.valueOf(txtNgayThue.getText());
        String MaKH=cboMaKH.getSelectedItem().toString();
        int ThoiHan=Integer.parseInt(txtThoiHan.getText());
        double TongTien=Double.parseDouble(txtTongTien.getText());
         PhieuThueBL.SuaPT(MaPT,MaNV,NgayThue,MaKH,ThoiHan);
      int tb=JOptionPane.showConfirmDialog(this, "Bạn muốn sửa lại phiếu thuê "+txtMaPT.getText()+" chứ ?","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(tb==JOptionPane.YES_OPTION)
        {
        JOptionPane.showMessageDialog(rootPane, "Sửa thành công");
        
        model =(DefaultTableModel)tblPT.getModel();
        model.setRowCount(0);
        initPhieuThue();
        ResetAll();
        }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
    int tb=JOptionPane.showConfirmDialog(this, "Bạn muốn xóa phiếu thuê "+txtMaPT.getText()+" chứ ?","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(tb==JOptionPane.YES_OPTION)
        {
            JOptionPane.showMessageDialog(rootPane,"Đã xóa thành công");
            PhieuThueBL.XoaPT(txtMaPT.getText());
        model =(DefaultTableModel)tblPT.getModel();
        model.setRowCount(0);
       initPhieuThue();
        ResetAll();  
 
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
      ResetAll();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        String ma=txtMaPT.getText();
        PhieuThueBL pt=new PhieuThueBL();
        PhieuThue b=pt.checkMaPT(txtMaPT.getText());
        String NgayTh=txtNgayThue.getText();
        if(txtMaPT.getText().equals(""))
        {
           JOptionPane.showMessageDialog(this, "Vui lòng nhập mã phiếu thuê! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtMaPT.requestFocus();
        }
          else if(!ma.matches("PT[0-9]{3}"))
        {
          JOptionPane.showMessageDialog(this, "Mã phiếu thuê phải định dạng PTxxx!.\nVí dụ PT001","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtMaPT.requestFocus();
        }
          else if(b!=null)
        {
             JOptionPane.showMessageDialog(null, "Mã phiếu thuê này đã tồn tại vui lòng chọn mã khác ","Thông báo",JOptionPane.WARNING_MESSAGE);
              txtMaPT.requestFocus();
                
        }  
        else if(cboMaNV.getSelectedItem().equals("------Chọn--------"))
        {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn mã nhân viên !","Thông báo",JOptionPane.WARNING_MESSAGE);
            cboMaNV.requestFocus();   
        }
         else if(txtNgayThue.getText().equals(""))
        {
           JOptionPane.showMessageDialog(this, "Vui lòng nhập ngày thuê! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtNgayThue.requestFocus();
        }
        else if(!NgayTh.matches("^\\d{4}\\-(0[1-9]|1[012])\\-(0[1-9]|[12][0-9]|3[01])$"))
        {
           JOptionPane.showMessageDialog(rootPane,"'"+txtNgayThue.getText()+"'"+" không đúng định định dạng ngày thuê.\nPhải nhập đúng định dạng yyyy-MM-dd","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtNgayThue.requestFocus();  
        }
        else if(cboMaKH.getSelectedItem().equals("------Chọn--------"))
        {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn mã khách hàng !","Thông báo",JOptionPane.WARNING_MESSAGE);
            cboMaKH.requestFocus();   
        }
        else if(txtThoiHan.getText().equals(""))
        {
           JOptionPane.showMessageDialog(this, "Vui lòng nhập thời hạn trả! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtThoiHan.requestFocus();
        }
       
        else
        {
        String MaPT=txtMaPT.getText();
        String MaNV=cboMaNV.getSelectedItem().toString();
        Date NgayThue=Date.valueOf(txtNgayThue.getText());
        String MaKH=cboMaKH.getSelectedItem().toString();
      int ThoiHan=Integer.parseInt(txtThoiHan.getText());
       double TongTien=Double.parseDouble(txtTongTien.getText());
         PhieuThue a=new PhieuThue(MaPT,MaNV,NgayThue,MaKH,ThoiHan,TongTien);
        int smt=PhieuThueBL.themPT(a);
         if(smt>0)
         {
        JOptionPane.showMessageDialog(rootPane, "Lưu phiếu thuê "+txtMaPT.getText()+" thành công");
        model =(DefaultTableModel)tblPT.getModel();
        model.setRowCount(0);
        initPhieuThue();
        ResetAll();
        }
         else
        JOptionPane.showMessageDialog(rootPane,"Lưu không thành công","Thông báo",JOptionPane.WARNING_MESSAGE);
        }
    
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnCTPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCTPTActionPerformed
        int row=tblPT.getSelectedRow();
        if(row>-1)
        {       
        List<ChiTietPhieuThue>listCTPT;
       String ma=txtMaPT.getText();
       listCTPT=ChiTietPhieuThueBL.dsCTPT(ma);
       FrmChiTietPhieuThue ctpt=new FrmChiTietPhieuThue();
       ctpt.txtMaPT1.setText(txtMaPT.getText());
       ctpt.txtThoiHan.setText(txtThoiHan.getText());
       ctpt.txtTongTien.setText(txtTongTien.getText());
       DefaultTableModel model2=(DefaultTableModel)ctpt.tblThongTin.getModel();
         
            for(ChiTietPhieuThue ct:listCTPT)
            {
               
                model2.addRow(new Object[]{ct.getStrMaBD(),ct.getStrTenBD(),ct.getIntSL(),ct.getDbDonGia(),ct.getFltGiamGia(),ct.getDbThanhTien()});
               
            }
        ctpt.setVisible(true);
      this.dispose();  
        }
        else
            JOptionPane.showMessageDialog(rootPane,"Vui lòng click vào 1 dòng trước khi xem chi tiết phiếu thuê!","Thông báo",JOptionPane.WARNING_MESSAGE);
            
    }//GEN-LAST:event_btnCTPTActionPerformed

    private void tblPTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPTMouseClicked

        int row=tblPT.getSelectedRow();
        if(row>-1)
        {
        btnLuu.setEnabled(false);
        txtMaPT.setEnabled(false);
        btnXoa.setEnabled(true);
        btnSua.setEnabled(true);
        txtMaPT.setText(String.valueOf(model.getValueAt(tblPT.getSelectedRow(),0)));
        cboMaNV.setSelectedItem(String.valueOf(model.getValueAt(tblPT.getSelectedRow(),1)));
        txtNgayThue.setText(String.valueOf(model.getValueAt(tblPT.getSelectedRow(),2)));
        cboMaKH.setSelectedItem(String.valueOf(model.getValueAt(tblPT.getSelectedRow(),3)));
       txtThoiHan.setText(String.valueOf(model.getValueAt(tblPT.getSelectedRow(),4)));
       txtTongTien.setText(String.valueOf(model.getValueAt(tblPT.getSelectedRow(),5)));
        }
       else
          JOptionPane.showMessageDialog(rootPane,"Vui lòng click vào 1 dòng!","Thông báo",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_tblPTMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
            btnXoa.setEnabled(false);
        btnSua.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void cboMaNVItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMaNVItemStateChanged
       initTenNV();
    }//GEN-LAST:event_cboMaNVItemStateChanged

    private void cboMaKHItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMaKHItemStateChanged
        initTenKH();
    }//GEN-LAST:event_cboMaKHItemStateChanged

    private void cboMaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaKHActionPerformed
          if(cboMaKH.getSelectedItem().equals("------Chọn--------"))
        {
            txtTenKH.setText("");
        }   
    }//GEN-LAST:event_cboMaKHActionPerformed

    private void txtTenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKHActionPerformed
          
    }//GEN-LAST:event_txtTenKHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPhieuThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPhieuThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPhieuThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPhieuThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPhieuThue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCTPT;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboMaKH;
    private javax.swing.JComboBox<String> cboMaNV;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPT;
    private javax.swing.JTextField txtMaPT;
    private javax.swing.JTextField txtNgayThue;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtThoiHan;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
