/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import businessLayer.PhieuPhatBL;
import businessLayer.TraBangDiaBL;
import dataTransferObject.PhieuPhat;
import dataTransferObject.TraBangDia;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mhuy2
 */
public class FrmPhieuPhat extends javax.swing.JFrame {

    /**
     * Creates new form FrmPhieuPhat
     */
    public FrmPhieuPhat() {
        initComponents();
        initMaTraQuaHan();
        initPhieuPhat();
    }
    DefaultTableModel model;
    void initPhieuPhat()
    {
        List<PhieuPhat> listHD;
       listHD=PhieuPhatBL.dsPhieuPhat();
        if(listHD.size()>0)
        {
            model=(DefaultTableModel)tblPhieuPhat.getModel();
            for(PhieuPhat hd:listHD)
            {
               
                model.addRow(new Object[]{hd.getStrMaPP(),hd.getStrMaTra(),hd.getStrMaPT(),hd.getStrTenKH(),hd.getIntSoNgayQuaHan(),hd.getDbTongTien()});
               
            }
    }
}
void initMaTraQuaHan()
{
    List<TraBangDia>listt;
    listt=TraBangDiaBL.dsTraBangDiaQuaHan();
    if(listt.size()>0)
    {
        for(TraBangDia a:listt)
        {
            cboMaTra.addItem(String.valueOf(a.getStrMaTra()));
        }
    }
}
private void initThongTinMaTra()
{
    List<PhieuPhat>list;
   String ma=cboMaTra.getSelectedItem().toString();
    list=PhieuPhatBL.HienThiThongTinPhieuTra(ma);
    if(list.size()>0)
    {
       
        for(PhieuPhat a:list)
        {
           
            txtMaPT.setText(a.getStrMaPT());
            txtTenKH.setText(a.getStrTenKH());
        }
    }
}
void ResetAll()
{
    txtMaPP.setEnabled(true);
    btnLuu.setEnabled(true);
    btnSua.setEnabled(false);
    btnXoa.setEnabled(false);
    txtMaPP.setText("");
    cboMaTra.setSelectedItem("------Chọn--------");
    txtSoNgay.setText("");
    tblPhieuPhat.clearSelection();
    txtTongTienPhat.setText("0");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMaPP = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtMaPT = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnTinhTienPhat = new javax.swing.JButton();
        txtTongTienPhat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cboMaTra = new javax.swing.JComboBox<>();
        txtTenKH = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtSoNgay = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPhieuPhat = new javax.swing.JTable();
        btnLuu = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phiếu phạt");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin phiếu phạt", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 51, 153))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Mã  trả quá hạn trả:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 120, 30));

        txtMaPP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtMaPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaPPActionPerformed(evt);
            }
        });
        jPanel3.add(txtMaPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 180, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Mã phiếu phạt:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Ngày");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, -1, 30));

        txtMaPT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtMaPT.setEnabled(false);
        jPanel3.add(txtMaPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 180, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Số ngày quá hạn");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, 30));

        btnTinhTienPhat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTinhTienPhat.setText("Tính ");
        btnTinhTienPhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhTienPhatActionPerformed(evt);
            }
        });
        jPanel3.add(btnTinhTienPhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 70, 30));

        txtTongTienPhat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtTongTienPhat.setText("0");
        txtTongTienPhat.setEnabled(false);
        jPanel3.add(txtTongTienPhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 120, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Tên khách hàng:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 30));

        cboMaTra.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cboMaTra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------Chọn--------" }));
        cboMaTra.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMaTraItemStateChanged(evt);
            }
        });
        cboMaTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaTraActionPerformed(evt);
            }
        });
        jPanel3.add(cboMaTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 180, 30));

        txtTenKH.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtTenKH.setEnabled(false);
        jPanel3.add(txtTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 180, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setText("Mã phiếu thuê:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, 30));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setText("1 ngày quá hạn =5000");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, 30));

        txtSoNgay.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSoNgay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSoNgayMouseClicked(evt);
            }
        });
        txtSoNgay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSoNgayKeyTyped(evt);
            }
        });
        jPanel3.add(txtSoNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 120, 30));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setText("Tổng tiền phạt:");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 700, 210));

        jLabel2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("PHIẾU PHẠT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 120, 60));

        tblPhieuPhat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu phạt", "Mã  trả quá hạn trả", "Mã phiếu thuê", "Tên khách hàng", "Số ngày quá hạn", "Tổng tiền phạt"
            }
        ));
        tblPhieuPhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhieuPhatMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPhieuPhat);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 700, 120));

        btnLuu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sua.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        getContentPane().add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 110, 40));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 115, 40));

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 110, 40));

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add-icon .png"))); // NOI18N
        btnThem.setText("Làm mới");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 110, 40));

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modify.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background .jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaPPActionPerformed

    }//GEN-LAST:event_txtMaPPActionPerformed

    private void cboMaTraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMaTraItemStateChanged
        initThongTinMaTra();
    }//GEN-LAST:event_cboMaTraItemStateChanged

    private void cboMaTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaTraActionPerformed
     if(cboMaTra.getSelectedItem().equals("------Chọn--------"))
        {
            txtMaPT.setText("");
            txtTenKH.setText("");
            
        }               
    }//GEN-LAST:event_cboMaTraActionPerformed

    private void tblPhieuPhatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieuPhatMouseClicked
    int row=tblPhieuPhat.getSelectedRow();
        if(row>-1)
        {
        btnLuu.setEnabled(false);
        txtMaPT.setEnabled(false);
        btnXoa.setEnabled(true);
        btnSua.setEnabled(true);
        txtMaPP.setText(String.valueOf(model.getValueAt(tblPhieuPhat.getSelectedRow(),0)));
        cboMaTra.setSelectedItem(String.valueOf(model.getValueAt(tblPhieuPhat.getSelectedRow(),1)));
       txtSoNgay.setText(String.valueOf(model.getValueAt(tblPhieuPhat.getSelectedRow(),4)));
       txtTongTienPhat.setText(String.valueOf(model.getValueAt(tblPhieuPhat.getSelectedRow(),5)));
        }
       else
          JOptionPane.showMessageDialog(rootPane,"Vui lòng click vào 1 dòng!","Thông báo",JOptionPane.WARNING_MESSAGE);      
    }//GEN-LAST:event_tblPhieuPhatMouseClicked

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
     String ma=txtMaPP.getText();
        PhieuPhatBL a=new PhieuPhatBL();
         PhieuPhat mapp=a.checkMaPP(txtMaPP.getText());
         
      if(txtMaPP.getText().equals(""))
       {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã phiếu phạt! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtMaPP.requestFocus();     
       }
      else if(!ma.matches("PP[0-9]{3}"))
       {
           JOptionPane.showMessageDialog(this, "Mã phiếu phạt phải định dạng PPxxx!.\nVí dụ PP001 ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtMaPP.requestFocus();   
       }
        else if(mapp!=null)
        {
             JOptionPane.showMessageDialog(null, "Mã phiếu phạt này đã tồn tại vui lòng chọn mã khác ","Thông báo",JOptionPane.WARNING_MESSAGE);
              txtMaPP.requestFocus();
                
        }
        else if(cboMaTra.getSelectedItem().equals("------Chọn--------"))
       {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn mã trã quá han trả! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            cboMaTra.requestFocus();     
       }
        
      else if(txtSoNgay.getText().equals("")||txtSoNgay.getText().equals("0"))
       {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số ngày quá hạn! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtSoNgay.requestFocus();     
       }
      else if(txtTongTienPhat.getText().equals("0")||txtTongTienPhat.getText().equals(""))
      {
          JOptionPane.showMessageDialog(this, "Vui lòng tính tiền phạt! ","Thông báo",JOptionPane.WARNING_MESSAGE);
          btnTinhTienPhat.requestFocus();   
      }
       else
       {
        String MaPP=txtMaPP.getText();
        String MaTra=cboMaTra.getSelectedItem().toString();
       int SoNgay=Integer.parseInt(txtSoNgay.getText());
       double TongTienPhat=Double.parseDouble(txtTongTienPhat.getText());
         PhieuPhat s=new PhieuPhat(MaTra,MaTra,SoNgay,TongTienPhat);
     int smt= PhieuPhatBL.themPhieuPhat(s);
     if(smt>0)
     {
        JOptionPane.showMessageDialog(rootPane, "Lưu phiếu phạt "+txtMaPP.getText()+" thành công");
        model =(DefaultTableModel)tblPhieuPhat.getModel();
        model.setRowCount(0);
        initPhieuPhat();
        ResetAll();
     }
     else
        JOptionPane.showMessageDialog(rootPane,"Lưu thất bại","Thông báo",JOptionPane.WARNING_MESSAGE);

       }       

    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        FrmMain bd=new FrmMain();
        bd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
 int tb=JOptionPane.showConfirmDialog(this, "Bạn muốn xóa phiếu phạt "+txtMaPP.getText()+" chứ ?","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(tb==JOptionPane.YES_OPTION)
        {
            JOptionPane.showMessageDialog(rootPane,"Đã xóa thành công");
            PhieuPhatBL.XoaPhieuPhat(txtMaPP.getText());
        model =(DefaultTableModel)tblPhieuPhat.getModel();
        model.setRowCount(0);
       initPhieuPhat();
        ResetAll();  
 
        }       
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
    ResetAll();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
     
        
         if(cboMaTra.getSelectedItem().equals("------Chọn--------"))
       {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn mã quá hạn trả! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            cboMaTra.requestFocus();     
       }
       
      else if(txtSoNgay.getText().equals(""))
       {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số ngày quá hạn! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtSoNgay.requestFocus();     
       }
      else if(txtTongTienPhat.getText().equals("0")||txtTongTienPhat.getText().equals(""))
      {
          JOptionPane.showMessageDialog(this, "Vui lòng tính tiền phạt! ","Thông báo",JOptionPane.WARNING_MESSAGE);
          btnTinhTienPhat.requestFocus();   
      }
       else
       {
        String MaPP=txtMaPP.getText();
        String MaTra=cboMaTra.getSelectedItem().toString();
       int SoNgay=Integer.parseInt(txtSoNgay.getText());
       double TongTienPhat=Double.parseDouble(txtTongTienPhat.getText());
        PhieuPhatBL.SuaPhieuPhat(MaPP,MaTra,SoNgay,TongTienPhat);
      int tb=JOptionPane.showConfirmDialog(this, "Bạn muốn sửa lại phiếu phạt "+txtMaPP.getText()+" chứ ?","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(tb==JOptionPane.YES_OPTION)
        {
        JOptionPane.showMessageDialog(rootPane, "Sửa thành công");
        model =(DefaultTableModel)tblPhieuPhat.getModel();
        model.setRowCount(0);
        initPhieuPhat();
        ResetAll();
        }
         }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnTinhTienPhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhTienPhatActionPerformed
 

         if(txtSoNgay.getText().equals("")||txtSoNgay.getText().equals("0"))
        {
             JOptionPane.showMessageDialog(this, "Vui lòng nhập số ngày quá hạn trước khi tính tổng tiền phạt  ! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtSoNgay.requestFocus();
        }
        else
        {
        int SN=Integer.parseInt(txtSoNgay.getText());
       
        double tt=SN*5000;
        String doikieuString=String.format("%.1f", tt);
        txtTongTienPhat.setText(doikieuString);   
        }
    }//GEN-LAST:event_btnTinhTienPhatActionPerformed

    private void txtSoNgayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoNgayKeyTyped
        char c=evt.getKeyChar();
            if(!Character.isDigit(c))
            evt.consume();
    }//GEN-LAST:event_txtSoNgayKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       btnSua.setEnabled(false);
       btnXoa.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void txtSoNgayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSoNgayMouseClicked
       txtTongTienPhat.setText("0");
    }//GEN-LAST:event_txtSoNgayMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPhieuPhat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPhieuPhat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPhieuPhat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPhieuPhat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPhieuPhat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTinhTienPhat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboMaTra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPhieuPhat;
    private javax.swing.JTextField txtMaPP;
    private javax.swing.JTextField txtMaPT;
    private javax.swing.JTextField txtSoNgay;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTongTienPhat;
    // End of variables declaration//GEN-END:variables
}
