/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;
import businessLayer.KhachHangBL;
import dataTransferObject.KhachHang;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author mhuy2
 */
public class FrmQuanLyKhachHang extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyKhachHang
     */
    public FrmQuanLyKhachHang() {
        initComponents();
        initKhachHang();
    }
 DefaultTableModel model;
    void initKhachHang()
    {
        List<KhachHang> listKH;
       listKH=KhachHangBL.dsKhachHang();
        if(listKH.size()>0)
        {
            model=(DefaultTableModel)tblThongTinKH.getModel();
            for(KhachHang nv:listKH)
            {
               
                model.addRow(new Object[]{nv.getStrMaKH(),nv.getStrHoTen(),nv.getStrCMND(),nv.getStrPhai(),nv.getStrSDT(),nv.getStrDChi()});
            }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpPhai = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        txtTim = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThongTinKH = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        radNam = new javax.swing.JRadioButton();
        radNu = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        txtHoTenKH = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtCMND = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý khách hàng");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Tên khách hàng cần tìm:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, 30));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 530, 110, -1));

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modify.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 530, 110, -1));

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, 110, -1));

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add-icon .png"))); // NOI18N
        btnThem.setText("Làm mới");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 110, -1));

        btnLuu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sua.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        getContentPane().add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 110, -1));

        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/timkiem.png"))); // NOI18N
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        getContentPane().add(btnTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 317, 50, -1));

        txtTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimActionPerformed(evt);
            }
        });
        txtTim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTimKeyTyped(evt);
            }
        });
        getContentPane().add(txtTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 370, 30));

        tblThongTinKH.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblThongTinKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Họ tên", "CMND", "Giới tính", "Số điện thoại", "Địa chỉ"
            }
        ));
        tblThongTinKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongTinKHMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblThongTinKH);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 740, 132));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 51, 153))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Mã khách hàng:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Họ tên:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("CMND:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 30));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Giới tính", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 51, 153))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        radNam.setBackground(new java.awt.Color(153, 204, 255));
        grpPhai.add(radNam);
        radNam.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        radNam.setSelected(true);
        radNam.setText("Nam");
        radNam.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(radNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 24, -1, -1));

        radNu.setBackground(new java.awt.Color(153, 204, 255));
        grpPhai.add(radNu);
        radNu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        radNu.setText("Nữ");
        jPanel2.add(radNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 24, -1, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 120, 60));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Số điện thoại:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Địa chỉ:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 30));

        txtMaKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(txtMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 301, 30));

        txtHoTenKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtHoTenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenKHActionPerformed(evt);
            }
        });
        jPanel3.add(txtHoTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 301, 30));

        txtDiaChi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 183, 540, 30));

        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });
        txtSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSDTKeyTyped(evt);
            }
        });
        jPanel3.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 301, 30));

        txtCMND.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCMND.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCMNDKeyTyped(evt);
            }
        });
        jPanel3.add(txtCMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 301, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 740, 230));

        jLabel2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("QUẢN LÝ KHÁCH HÀNG");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background .jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents
void ResetAll()
{
    txtTim.setText("");
    txtMaKH.setEnabled(true);
    txtMaKH.setText("");
    txtHoTenKH.setText("");
    txtCMND.setText("");
    radNam.setSelected(true);
    radNu.setSelected(false);
    txtSDT.setText("");
    txtDiaChi.setText("");
    tblThongTinKH.clearSelection();
    btnXoa.setEnabled(false);
    btnSua.setEnabled(false);
    btnLuu.setEnabled(true);
    model =(DefaultTableModel)tblThongTinKH.getModel();
    model.setRowCount(0);
    initKhachHang();
}
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        FrmMain all=new FrmMain();
        all.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed

        if(txtHoTenKH.getText().equals(""))
       {
           JOptionPane.showMessageDialog(this, "Vui lòng nhập họ tên khách hàng! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtHoTenKH.requestFocus();
       }
        else if(txtCMND.getText().equals(""))
       {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập CMND! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtCMND.requestFocus();   
       }
       else if(txtCMND.getText().length()<9|txtCMND.getText().length()>12|txtCMND.getText().length()==10|txtCMND.getText().length()==11)
       {
            JOptionPane.showMessageDialog(this, "CMND phải 9 số hoặc 12 số! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtCMND.requestFocus();   
       }
       else if(txtSDT.getText().equals(""))
       {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtSDT.requestFocus();     
       }
       else if(txtSDT.getText().length()<10|txtSDT.getText().length()>11)
       {
        JOptionPane.showMessageDialog(this, "Số điện thoại phải 10 số hoặc 11 số! ","Thông báo",JOptionPane.WARNING_MESSAGE);
        txtSDT.requestFocus(); 
        }
      
       else if(txtDiaChi.getText().equals(""))
       {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập địa chỉ! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtDiaChi.requestFocus();     
       }
        else
       {
        String MaKH=txtMaKH.getText();
     String hoten=txtHoTenKH.getText();
     String cmnd=txtCMND.getText();
       String gt=radNam.isSelected()?"Nam":"Nữ";
       String SDT=txtSDT.getText();
       String DChi=txtDiaChi.getText();
       KhachHang s=new KhachHang(MaKH,hoten,cmnd,gt,SDT,DChi);
     int tb=JOptionPane.showConfirmDialog(this, "Bạn muốn sửa lại khách hàng "+txtHoTenKH.getText()+ " này chứ ?","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(tb==JOptionPane.YES_OPTION)
        {
            JOptionPane.showMessageDialog(rootPane,"Đã sửa thành công");
           KhachHangBL.SuaKhachHang(s);
        model =(DefaultTableModel)tblThongTinKH.getModel();
        model.setRowCount(0);
        initKhachHang();
         ResetAll();
        }   
       }

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        String ma=txtMaKH.getText();
     KhachHangBL kh=new KhachHangBL();
         KhachHang a=kh.checkMaKH(txtMaKH.getText());
      if(txtMaKH.getText().equals(""))
       {
           JOptionPane.showMessageDialog(this, "Vui lòng điển mã khách hàng! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtMaKH.requestFocus();
       }
     
           else  if(!ma.matches("KH[0-9]{3}"))
     {
          JOptionPane.showMessageDialog(this, "Mã khách hàng phải định dạng KHxxx!.\nVí dụ KH001","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtMaKH.requestFocus();
     }
             else if(a!=null)
         {
             JOptionPane.showMessageDialog(null, "Mã khách hàng này đã tồn tại vui lòng chọn mã khác ","Thông báo",JOptionPane.WARNING_MESSAGE);
              txtMaKH.requestFocus();
                
         }
       else if(txtHoTenKH.getText().equals(""))
       {
           JOptionPane.showMessageDialog(this, "Vui lòng nhập họ tên khách hàng! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtHoTenKH.requestFocus();
       }
        else if(txtCMND.getText().equals(""))
       {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập CMND! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtCMND.requestFocus();   
       }
       else if(txtCMND.getText().length()<9|txtCMND.getText().length()>12|txtCMND.getText().length()==10|txtCMND.getText().length()==11)
       {
            JOptionPane.showMessageDialog(this, "CMND phải 9 số hoặc 12 số! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtCMND.requestFocus();   
       }
       else if(txtSDT.getText().equals(""))
       {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtSDT.requestFocus();     
       }
       else if(txtSDT.getText().length()<10|txtSDT.getText().length()>11)
       {
        JOptionPane.showMessageDialog(this, "Số điện thoại phải 10 số hoặc 11 số! ","Thông báo",JOptionPane.WARNING_MESSAGE);
        txtSDT.requestFocus(); 
        }
      
       else if(txtDiaChi.getText().equals(""))
       {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập địa chỉ! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtDiaChi.requestFocus();     
       }
        else
       {
        String MaKH=txtMaKH.getText();
     String hoten=txtHoTenKH.getText();
     String cmnd=txtCMND.getText();
       String gt=radNam.isSelected()?"Nam":"Nữ";
       String SDT=txtSDT.getText();
       String DChi=txtDiaChi.getText();
       KhachHang s=new KhachHang(MaKH,hoten,cmnd,gt,SDT,DChi);
     int smt= KhachHangBL.themKhachHang(s);
     if(smt>0)
     {
         
        JOptionPane.showMessageDialog(rootPane, "Lưu khách hàng "+txtHoTenKH.getText()+" thành công");
        model =(DefaultTableModel)tblThongTinKH.getModel();
        model.setRowCount(0);
        initKhachHang();
         ResetAll();
     }
     else
       JOptionPane.showMessageDialog(rootPane,"Lưu thất bại","Thông báo",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
    ResetAll();
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblThongTinKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongTinKHMouseClicked
        int row=tblThongTinKH.getSelectedRow();
        if(row>-1)
        {
        txtMaKH.setEnabled(false);
        btnXoa.setEnabled(true);
        btnSua.setEnabled(true);
        btnLuu.setEnabled(false);
        txtMaKH.setText(String.valueOf(model.getValueAt(tblThongTinKH.getSelectedRow(),0)));
        txtHoTenKH.setText(String.valueOf(model.getValueAt(tblThongTinKH.getSelectedRow(),1)));
        txtCMND.setText(String.valueOf(model.getValueAt(tblThongTinKH.getSelectedRow(),2)));
        String gt=tblThongTinKH.getValueAt(row, 3).toString();
        if(gt.equalsIgnoreCase("Nam"))
        {
            radNam.setSelected(true);
            radNu.setSelected(false);
        }  else
        {
            radNu.setSelected(true);
            radNam.setSelected(false);
        }
        
        txtSDT.setText(String.valueOf(model.getValueAt(tblThongTinKH.getSelectedRow(),4)));
        txtDiaChi.setText(String.valueOf(model.getValueAt(tblThongTinKH.getSelectedRow(),5)));
        }
        else
             JOptionPane.showMessageDialog(rootPane,"Vui lòng click vào 1 dòng!","Thông báo",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_tblThongTinKHMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
      
     int tb=JOptionPane.showConfirmDialog(this, "Bạn muốn xóa khách hàng "+txtHoTenKH.getText()+ " chứ ?","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(tb==JOptionPane.YES_OPTION)
        {
           KhachHangBL.XoaKH(txtMaKH.getText());
            JOptionPane.showMessageDialog(rootPane,"Đã xóa thành công");
        model =(DefaultTableModel)tblThongTinKH.getModel();
        model.setRowCount(0);
        initKhachHang();
        ResetAll();;
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    btnXoa.setEnabled(false);
    btnSua.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void txtCMNDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCMNDKeyTyped
        char c=evt.getKeyChar();
            if(!Character.isDigit(c))
            evt.consume();
    }//GEN-LAST:event_txtCMNDKeyTyped

    private void txtSDTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSDTKeyTyped
        char c=evt.getKeyChar();
            if(!Character.isDigit(c))
            evt.consume();
    }//GEN-LAST:event_txtSDTKeyTyped

    private void txtTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimActionPerformed

    private void txtTimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKeyReleased

    }//GEN-LAST:event_txtTimKeyReleased

    private void txtTimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKeyTyped

    }//GEN-LAST:event_txtTimKeyTyped

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed

        if(txtTim.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Vui lòng điển họ tên khách hàng cần tìm ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtTim.requestFocus();
        }
        else
        {

            List<KhachHang> listKH;
            String hoten=txtTim.getText();
            listKH=KhachHangBL.timkiemKH(hoten);
            model =(DefaultTableModel)tblThongTinKH.getModel();
                model.setRowCount(0);
            if(listKH.size()<=0)
            {

                JOptionPane.showMessageDialog(rootPane,"Không tìm thấy khách hàng !");
                

            }
            else

            for(KhachHang s:listKH)
            {
                
                model.addRow(new Object[]{s.getStrMaKH(),s.getStrHoTen(),s.getStrCMND(),s.getStrPhai(),s.getStrSDT(),s.getStrDChi()});
            }
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void txtHoTenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenKHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmQuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmQuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmQuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmQuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmQuanLyKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup grpPhai;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton radNam;
    private javax.swing.JRadioButton radNu;
    private javax.swing.JTable tblThongTinKH;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHoTenKH;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
