/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import businessLayer.PhieuThueBL;
import businessLayer.TraBangDiaBL;
import dataTransferObject.PhieuThue;
import dataTransferObject.TraBangDia;
import java.sql.Date;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.parser.TokenType;

/**
 *
 * @author mhuy2
 */
public class FrmTraBangDia extends javax.swing.JFrame {

    /**
     * Creates new form FrmTraBangDia
     */
    public FrmTraBangDia() {
        initComponents();
        initMaPT();
        initPhieuTra();
    }
DefaultTableModel model;
void initPhieuTra()
{
    
        List<TraBangDia> listT;
       listT=TraBangDiaBL.dsTraBangDia();
        if(listT.size()>0)
        {
            model=(DefaultTableModel)tblTra.getModel();
            for(TraBangDia hd:listT)
            {
               
                model.addRow(new Object[]{hd.getStrMaTra(),hd.getStrMaPT(),hd.getStrMaKH(),hd.getStrTenKH(),hd.getstrNgayThue(),hd.getIntThoiHan(),hd.getStrQuaHan()});
               
            }
        }
}

void initMaPT()
{
    List<PhieuThue>listPT;
    listPT=PhieuThueBL.dsPhieuThue();
    if(listPT.size()>0)
    {
        for(PhieuThue a:listPT)
        {
            cboMaPT.addItem(String.valueOf(a.getStrMaPT()));
        }
    }
}
private void ThongTinPT()
{
    List<TraBangDia>listPT;
   String ma=cboMaPT.getSelectedItem().toString();
    listPT=TraBangDiaBL.HienThiThongTinPhieuThue(ma);
    if(listPT.size()>0)
    {
       
        for(TraBangDia a:listPT)
        {
           
            txtMaKH.setText(a.getStrMaKH());
            txtTenKH.setText(String.valueOf(a.getStrTenKH()));
            txtNgayThue.setText(String.valueOf(a.getstrNgayThue()));
            txtThoiHan.setText(Integer.toString(a.getIntThoiHan()));
        }
    }
}
void ResetAll()
{
     txtMaTra.setEnabled(true);
     txtMaTra.setText("");
    cboMaPT.setSelectedItem("------Chọn--------");
    cboQuaHan.setSelectedItem("------Chọn--------");
    btnXoa.setEnabled(false);
    btnSua.setEnabled(false);
    btnLuu.setEnabled(true);
    tblTra.clearSelection();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaTra = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cboQuaHan = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtThoiHan = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtNgayThue = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cboMaPT = new javax.swing.JComboBox<>();
        txtMaKH = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTra = new javax.swing.JTable();
        btnLuu = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trả băng đĩa");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin trả đĩa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 51, 153))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Mã phiếu thuê:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Quá hạn:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, 30));

        txtMaTra.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtMaTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaTraActionPerformed(evt);
            }
        });
        jPanel3.add(txtMaTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 180, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Mã Trả:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, 30));

        cboQuaHan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cboQuaHan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------Chọn--------", "Có", "Không" }));
        cboQuaHan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboQuaHanItemStateChanged(evt);
            }
        });
        cboQuaHan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboQuaHanActionPerformed(evt);
            }
        });
        jPanel3.add(cboQuaHan, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 170, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Ngày");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, -1, 30));

        txtThoiHan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtThoiHan.setEnabled(false);
        jPanel3.add(txtThoiHan, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 130, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Ngày thuê:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, 30));

        txtNgayThue.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtNgayThue.setEnabled(false);
        jPanel3.add(txtNgayThue, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 170, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Mã khách hàng:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 30));

        cboMaPT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cboMaPT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------Chọn--------" }));
        cboMaPT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMaPTItemStateChanged(evt);
            }
        });
        cboMaPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaPTActionPerformed(evt);
            }
        });
        jPanel3.add(cboMaPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 180, 30));

        txtMaKH.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtMaKH.setEnabled(false);
        jPanel3.add(txtMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 180, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setText("Thời hạn trả:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, 30));

        txtTenKH.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtTenKH.setEnabled(false);
        jPanel3.add(txtTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 170, 30));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setText("Tên khách hàng:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 660, 200));

        jLabel2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("TRẢ BĂNG ĐĨA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 150, 50));

        tblTra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã trả", "Mã phiếu thuê", "Mã khách hàng", "Tên khách hàng", "Ngày thuê", "Thời hạn trả", "Quá hạn"
            }
        ));
        tblTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTraMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTra);
        if (tblTra.getColumnModel().getColumnCount() > 0) {
            tblTra.getColumnModel().getColumn(6).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 660, 120));

        btnLuu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sua.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        getContentPane().add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 110, 40));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 115, 40));

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 110, 40));

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add-icon .png"))); // NOI18N
        btnThem.setText("Làm mới");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 110, 40));

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modify.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background .jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaTraActionPerformed

    }//GEN-LAST:event_txtMaTraActionPerformed

    private void cboQuaHanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboQuaHanItemStateChanged
     
    }//GEN-LAST:event_cboQuaHanItemStateChanged

    private void cboQuaHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboQuaHanActionPerformed
      
    }//GEN-LAST:event_cboQuaHanActionPerformed

    private void cboMaPTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMaPTItemStateChanged
        ThongTinPT();
    }//GEN-LAST:event_cboMaPTItemStateChanged

    private void cboMaPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaPTActionPerformed
        if(cboMaPT.getSelectedItem().equals("------Chọn--------"))
        {
            txtMaKH.setText("");
            txtTenKH.setText("");
            txtNgayThue.setText("");
            txtThoiHan.setText("");
        }        
    }//GEN-LAST:event_cboMaPTActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
    ResetAll();   
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
 
        String ma=txtMaTra.getText();
        TraBangDiaBL a=new TraBangDiaBL();
        TraBangDia matra=a.checkMaTra(txtMaTra.getText());
      if(txtMaTra.getText().equals(""))
       {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã trả! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtMaTra.requestFocus();     
       }
      else if(!ma.matches("TR[0-9]{3}"))
       {
           JOptionPane.showMessageDialog(this, "Mã trả phải định dạng TRxxx!.\nVí dụ TR001 ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtMaTra.requestFocus();   
       }
        else if(matra!=null)
        {
             JOptionPane.showMessageDialog(null, "Mã trả này đã tồn tại vui lòng chọn mã khác ","Thông báo",JOptionPane.WARNING_MESSAGE);
              txtMaTra.requestFocus();
                
        }
        else if(cboMaPT.getSelectedItem().equals("------Chọn--------"))
       {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn mã phiếu thuê! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtMaTra.requestFocus();     
       }
      else if(cboQuaHan.getSelectedItem().equals("------Chọn--------"))
       {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn quá hạn! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtMaTra.requestFocus();     
       }
       else
       {
        String MaTra=txtMaTra.getText();
        String MaPT=cboMaPT.getSelectedItem().toString();
       String QuaHan=cboQuaHan.getSelectedItem().toString();
    TraBangDia s=new TraBangDia(MaTra,MaPT,QuaHan);
     int smt= TraBangDiaBL.themTraBangDia(s);
     if(smt>0)
     {
        JOptionPane.showMessageDialog(rootPane, "Lưu trả băng đĩa "+txtMaTra.getText()+" thành công");
        model =(DefaultTableModel)tblTra.getModel();
        model.setRowCount(0);
        initPhieuTra();
        ResetAll();
     }
     else
        JOptionPane.showMessageDialog(rootPane,"Lưu thất bại","Thông báo",JOptionPane.WARNING_MESSAGE);

       }            
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
         int tb=JOptionPane.showConfirmDialog(this, "Bạn muốn xóa trả băng đĩa"+txtMaTra.getText()+" chứ ?","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(tb==JOptionPane.YES_OPTION)
        {
            JOptionPane.showMessageDialog(rootPane,"Đã xóa thành công");
           TraBangDiaBL.XoaTraBangDia(txtMaTra.getText());
        model =(DefaultTableModel)tblTra.getModel();
        model.setRowCount(0);
        initPhieuTra();
        ResetAll();  
        }
       
        
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if(cboMaPT.getSelectedItem().equals("------Chọn--------"))
       {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn mã phiếu thuê! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtMaTra.requestFocus();     
       }
      else if(cboQuaHan.getSelectedItem().equals("------Chọn--------"))
       {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn quá hạn! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtMaTra.requestFocus();     
       }
       else
       {
        String MaTra=txtMaTra.getText();
        String MaPT=cboMaPT.getSelectedItem().toString();
       String QuaHan=cboQuaHan.getSelectedItem().toString();
    TraBangDiaBL.SuaTraBangDia(MaTra,MaPT,QuaHan);
      int tb=JOptionPane.showConfirmDialog(this, "Bạn muốn sửa lại trả băng đĩa "+txtMaTra.getText()+" chứ ?","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(tb==JOptionPane.YES_OPTION)
        {
        JOptionPane.showMessageDialog(rootPane, "Sửa thành công");
        model =(DefaultTableModel)tblTra.getModel();
        model.setRowCount(0);
        initPhieuTra();
        ResetAll();
         }  
       }            
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        FrmMain bd=new FrmMain();
        bd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTraMouseClicked
        int row=tblTra.getSelectedRow();
        if(row>-1)
        {
        txtMaTra.setEnabled(false);
        btnXoa.setEnabled(true);
        btnSua.setEnabled(true);
        btnLuu.setEnabled(false);
        txtMaTra.setText(String.valueOf(model.getValueAt(tblTra.getSelectedRow(),0)));
        cboMaPT.setSelectedItem(String.valueOf(model.getValueAt(tblTra.getSelectedRow(),1)));
         cboQuaHan.setSelectedItem(String.valueOf(model.getValueAt(tblTra.getSelectedRow(),6)));
        }
        else
             JOptionPane.showMessageDialog(rootPane,"Vui lòng click vào 1 dòng!","Thông báo",JOptionPane.WARNING_MESSAGE);
                                            

    }//GEN-LAST:event_tblTraMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        btnXoa.setEnabled(false);
        btnSua.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTraBangDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTraBangDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTraBangDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTraBangDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTraBangDia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboMaPT;
    private javax.swing.JComboBox<String> cboQuaHan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTra;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtMaTra;
    private javax.swing.JTextField txtNgayThue;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtThoiHan;
    // End of variables declaration//GEN-END:variables
}
