/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import businessLayer.BangDiaBL;
import businessLayer.ThongTinBaiHatBL;
import dataTransferObject.BangDia;
import dataTransferObject.ThongTinBaiHat;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import org.omg.PortableServer.IdAssignmentPolicy;

/**
 *
 * @author mhuy2
 */
public class FrmThongTinBangDiaChuaBaiHat extends javax.swing.JFrame {

    /**
     * Creates new form FrmThongTinBaiHat
     */
    public FrmThongTinBangDiaChuaBaiHat() {
        initComponents();
        initthongtinbh();
      
      
    }
    
   DefaultTableModel model;
    String id;
  void initthongtinbh()
  {
       List<ThongTinBaiHat>listBH;
       String maString=txtMaBD1.getText();
       listBH=ThongTinBaiHatBL.dsBH(maString);
        
       
           model=(DefaultTableModel)tblBaiHat.getModel();
         
            for(ThongTinBaiHat bh:listBH)
            {
                
                model.addRow(new Object[]{bh.getID(),bh.getStrTenBai(),bh.getStrCaSi(),bh.getStrNhacSi(),bh.getStrMaBD()});
            }
  }

   void ResetAll()
   {
       btnLuu.setEnabled(true);
     txtTenBH.setText("");
    txtCaSi.setText("");
    txtNhacSi.setText("");
    tblBaiHat.clearSelection();
    btnXoa.setEnabled(false);
    btnSua.setEnabled(false);
   }

      
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltieude = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaBD1 = new javax.swing.JTextField();
        txtCaSi = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtNhacSi = new javax.swing.JTextField();
        txtTenBH = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBaiHat = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thông tin bài hát");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltieude.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lbltieude.setForeground(new java.awt.Color(0, 0, 153));
        getContentPane().add(lbltieude, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 710, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Mã băng đĩa:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 96, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Ca sĩ:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 161, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Nhạc sĩ:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 195, -1, -1));

        txtMaBD1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtMaBD1.setEnabled(false);
        getContentPane().add(txtMaBD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 150, -1));

        txtCaSi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtCaSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 158, 450, -1));

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add-icon .png"))); // NOI18N
        btnThem.setText("Làm mới");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 110, 40));

        btnLuu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sua.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        getContentPane().add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 110, 40));

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 110, 40));

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modify.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 110, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Tên bài hát:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 127, -1, -1));

        txtNhacSi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtNhacSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 192, 450, -1));

        txtTenBH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtTenBH, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 124, 450, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 115, 40));

        tblBaiHat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Tên bài hát", "Ca sĩ", "Nhạc sĩ", "Mã băng đĩa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBaiHat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBaiHatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBaiHat);
        if (tblBaiHat.getColumnModel().getColumnCount() > 0) {
            tblBaiHat.getColumnModel().getColumn(0).setMinWidth(0);
            tblBaiHat.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblBaiHat.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 700, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background .jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
         FrmQuanLyBangDia bd=new FrmQuanLyBangDia();
        bd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblBaiHatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBaiHatMouseClicked
        int row=tblBaiHat.getSelectedRow();
        if(row>-1)
        {
        btnLuu.setEnabled(false);
        btnXoa.setEnabled(true);
        btnSua.setEnabled(true);
           id=String.valueOf(model.getValueAt(tblBaiHat.getSelectedRow(),0));
        txtTenBH.setText(String.valueOf(model.getValueAt(tblBaiHat.getSelectedRow(),1)));
        txtCaSi.setText(String.valueOf(model.getValueAt(tblBaiHat.getSelectedRow(),2)));
         txtNhacSi.setText(String.valueOf(model.getValueAt(tblBaiHat.getSelectedRow(),3)));
            txtMaBD1.setText(String.valueOf(model.getValueAt(tblBaiHat.getSelectedRow(),4))); 
        }
        else
             JOptionPane.showMessageDialog(rootPane,"Vui lòng click vào 1 dòng!","Thông báo",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_tblBaiHatMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
       
     ResetAll();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        if(txtTenBH.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên bài hát! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtTenBH.requestFocus(); 
        }
        else if(txtCaSi.getText().equals(""))
        {
              JOptionPane.showMessageDialog(this, "Vui lòng nhập  ca sĩ! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtCaSi.requestFocus(); 
        }
        else if(txtNhacSi.getText().equals(""))
        {
             JOptionPane.showMessageDialog(this, "Vui lòng nhập  nhạc sĩ! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtNhacSi.requestFocus(); 
        }
        else
        {
        String ten=txtTenBH.getText();
        String Casi=txtCaSi.getText();
        String NhacSi=txtNhacSi.getText();
        String MaBD=txtMaBD1.getText();
        ThongTinBaiHat s=new ThongTinBaiHat(ten,Casi,NhacSi,MaBD);
        int smt= ThongTinBaiHatBL.themBaiHat(s);
     if(smt>0)
     {
         
        JOptionPane.showMessageDialog(rootPane, "Lưu thông tin bài hát thành công");
      
             model =(DefaultTableModel)tblBaiHat.getModel(); 
      model.setRowCount(0);
        initthongtinbh();
           ResetAll();
        }

        }
      
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
    if(txtTenBH.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên bài hát! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtTenBH.requestFocus(); 
        }
        else if(txtCaSi.getText().equals(""))
        {
              JOptionPane.showMessageDialog(this, "Vui lòng nhập  ca sĩ! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtCaSi.requestFocus(); 
        }
        else if(txtNhacSi.getText().equals(""))
        {
             JOptionPane.showMessageDialog(this, "Vui lòng nhập  nhạc sĩ! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtNhacSi.requestFocus(); 
        }
        else
        {
         String MaBD=txtMaBD1.getText();
         String Ten=txtTenBH.getText();
         String Casi=txtCaSi.getText();
             String NhacSi=txtNhacSi.getText();
        int ID=Integer.parseInt(id);
      ThongTinBaiHatBL.SuaBH(ID,Ten,Casi,NhacSi,MaBD);
       int tb=JOptionPane.showConfirmDialog(this, "Bạn muốn sửa lại dữ liệu này chứ ?","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(tb==JOptionPane.YES_OPTION)
        {
        JOptionPane.showMessageDialog(rootPane,"Cập nhật thành công");
        model =(DefaultTableModel)tblBaiHat.getModel();
        model.setRowCount(0);
        initthongtinbh();
        ResetAll();
        }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         btnXoa.setEnabled(false);
    btnSua.setEnabled(false);
     List<ThongTinBaiHat>listBH;
       String maString=txtMaBD1.getText();
       listBH=ThongTinBaiHatBL.dsBH(maString);
           model=(DefaultTableModel)tblBaiHat.getModel();
         
            for(ThongTinBaiHat bh:listBH)
            {
                model.addRow(new Object[]{bh.getID(),bh.getStrTenBai(),bh.getStrCaSi(),bh.getStrNhacSi(),bh.getStrMaBD()});
            }
    }//GEN-LAST:event_formWindowOpened
 
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
    
         int ID=Integer.parseInt(id);
        int tb=JOptionPane.showConfirmDialog(this,"Bạn có muốn xóa dữ liệu này không?","Thông báo",JOptionPane.YES_NO_OPTION);
          if(tb==JOptionPane.YES_OPTION)
          {
               JOptionPane.showMessageDialog(rootPane,"Đã xóa thành công");
              ThongTinBaiHatBL.XoaBH(ID);
              model =(DefaultTableModel)tblBaiHat.getModel();
            model.setRowCount(0);
            initthongtinbh();
            ResetAll();
          }
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmThongTinBangDiaChuaBaiHat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmThongTinBangDiaChuaBaiHat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmThongTinBangDiaChuaBaiHat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmThongTinBangDiaChuaBaiHat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmThongTinBangDiaChuaBaiHat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lbltieude;
    public javax.swing.JTable tblBaiHat;
    private javax.swing.JTextField txtCaSi;
    public javax.swing.JTextField txtMaBD1;
    public javax.swing.JTextField txtNhacSi;
    private javax.swing.JTextField txtTenBH;
    // End of variables declaration//GEN-END:variables
}
