/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import businessLayer.BangDiaThongTinBaiHatBL;
import businessLayer.ThongTinBaiHatBL;
import dataTransferObject.BangDiaThongTinBaiHat;
import dataTransferObject.ThongTinBaiHat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mhuy2
 */
public class FrmTimKiemThongTinBaiHat extends javax.swing.JFrame {

    /**
     * Creates new form FrmTimKiemCaSiNhacSi
     */
    public FrmTimKiemThongTinBaiHat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnChon = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongTinBD = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        radTenBD = new javax.swing.JRadioButton();
        radTenBaiHat = new javax.swing.JRadioButton();
        radCaSi = new javax.swing.JRadioButton();
        radNamSX = new javax.swing.JRadioButton();
        radNhacSi = new javax.swing.JRadioButton();
        radNuocSX = new javax.swing.JRadioButton();
        txtTim = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnTim = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tìm kiếm thông tin bài hát");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblThongTinBD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên băng đĩa", "Tên bài hát", "Ca sĩ", "Nhạc sĩ", "Nước sản xuất", "Năm sản xuất"
            }
        ));
        tblThongTinBD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongTinBDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblThongTinBD);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 730, 150));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm theo:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        radTenBD.setBackground(new java.awt.Color(204, 204, 255));
        btnChon.add(radTenBD);
        radTenBD.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        radTenBD.setSelected(true);
        radTenBD.setText("Tên băng đĩa");
        radTenBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radTenBDActionPerformed(evt);
            }
        });
        jPanel1.add(radTenBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        radTenBaiHat.setBackground(new java.awt.Color(204, 204, 255));
        btnChon.add(radTenBaiHat);
        radTenBaiHat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        radTenBaiHat.setText("Tên bài hát");
        jPanel1.add(radTenBaiHat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        radCaSi.setBackground(new java.awt.Color(204, 204, 255));
        btnChon.add(radCaSi);
        radCaSi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        radCaSi.setText("Ca sĩ");
        radCaSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCaSiActionPerformed(evt);
            }
        });
        jPanel1.add(radCaSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        radNamSX.setBackground(new java.awt.Color(204, 204, 255));
        btnChon.add(radNamSX);
        radNamSX.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        radNamSX.setText("Năm sản xuất");
        radNamSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radNamSXActionPerformed(evt);
            }
        });
        jPanel1.add(radNamSX, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        radNhacSi.setBackground(new java.awt.Color(204, 204, 255));
        btnChon.add(radNhacSi);
        radNhacSi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        radNhacSi.setText("Nhạc sĩ");
        radNhacSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radNhacSiActionPerformed(evt);
            }
        });
        jPanel1.add(radNhacSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        radNuocSX.setBackground(new java.awt.Color(204, 204, 255));
        btnChon.add(radNuocSX);
        radNuocSX.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        radNuocSX.setText("Nước sản xuất");
        radNuocSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radNuocSXActionPerformed(evt);
            }
        });
        jPanel1.add(radNuocSX, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 330, 120));

        txtTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimActionPerformed(evt);
            }
        });
        txtTim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTimKeyTyped(evt);
            }
        });
        getContentPane().add(txtTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 660, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("TÌM KIẾM THÔNG TIN BÀI HÁT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 280, 60));

        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/timkiem.png"))); // NOI18N
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        getContentPane().add(btnTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 213, 60, 40));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 115, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background .jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblThongTinBDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongTinBDMouseClicked

    }//GEN-LAST:event_tblThongTinBDMouseClicked

    private void radTenBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radTenBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radTenBDActionPerformed

    private void radCaSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCaSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radCaSiActionPerformed

    private void radNamSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radNamSXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radNamSXActionPerformed

    private void radNhacSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radNhacSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radNhacSiActionPerformed

    private void radNuocSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radNuocSXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radNuocSXActionPerformed

    private void txtTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimActionPerformed

    private void txtTimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKeyReleased

    }//GEN-LAST:event_txtTimKeyReleased

    private void txtTimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKeyTyped

    }//GEN-LAST:event_txtTimKeyTyped

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        if(txtTim.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập ô tìm kiếm! ","Thông báo",JOptionPane.WARNING_MESSAGE);
            txtTim.requestFocus();
        }
        else
        if(radTenBD.isSelected())
        {
            List<BangDiaThongTinBaiHat> listTT;
            String hoten=txtTim.getText();
            listTT=BangDiaThongTinBaiHatBL.timkiemTTBHtheoTenBD(hoten);
            model =(DefaultTableModel)tblThongTinBD.getModel();
                model.setRowCount(0);
            if(listTT.size()<=0)
            {
                
                JOptionPane.showMessageDialog(rootPane,"Không tìm thấy tên băng đĩa cần tìm!");
            }
            else
            for(BangDiaThongTinBaiHat s:listTT)
            {
               
                model.addRow(new Object[]{s.getStrTenBangDia(),s.getStrTenBaiHat(),s.getStrCaSi(),s.getStrNhacSi(),s.getStrNuocSX(),s.getIntNamSX()});
            }

        }
        if(radTenBaiHat.isSelected())
        {
            List<BangDiaThongTinBaiHat> listTT;
            String hoten=txtTim.getText();
            listTT=BangDiaThongTinBaiHatBL.timkiemTTBHtheoTenBaiHat(hoten);
            model =(DefaultTableModel)tblThongTinBD.getModel();
                model.setRowCount(0);
            if(listTT.size()<=0)
            {
                
                JOptionPane.showMessageDialog(rootPane,"Không tìm thấy tên bài hát cần tìm!");
            }
            else
          for(BangDiaThongTinBaiHat s:listTT)
            {
               
                model.addRow(new Object[]{s.getStrTenBangDia(),s.getStrTenBaiHat(),s.getStrCaSi(),s.getStrNhacSi(),s.getStrNuocSX(),s.getIntNamSX()});
            }

        }
        if(radCaSi.isSelected())
        {
            List<BangDiaThongTinBaiHat> listTT;
            String hoten=txtTim.getText();
            listTT=BangDiaThongTinBaiHatBL.timkiemTTBHtheoCaSi(hoten);
             model =(DefaultTableModel)tblThongTinBD.getModel();
                model.setRowCount(0);
            if(listTT.size()<=0)
            {
               
                JOptionPane.showMessageDialog(rootPane,"Không tìm thấy ca sĩ cần tìm !");
            }
            else
           for(BangDiaThongTinBaiHat s:listTT)
            {
                
                model.addRow(new Object[]{s.getStrTenBangDia(),s.getStrTenBaiHat(),s.getStrCaSi(),s.getStrNhacSi(),s.getStrNuocSX(),s.getIntNamSX()});
            }

        }
        if(radNhacSi.isSelected())
        {
           List<BangDiaThongTinBaiHat> listTT;
            String hoten=txtTim.getText();
            listTT=BangDiaThongTinBaiHatBL.timkiemTTBHtheoNhacSi(hoten);
                 model =(DefaultTableModel)tblThongTinBD.getModel();
                model.setRowCount(0);
            if(listTT.size()<=0)
            {
           
                JOptionPane.showMessageDialog(rootPane,"Không tìm thấy nhạc sĩ cần tìm !");
            }
            else
         for(BangDiaThongTinBaiHat s:listTT)
            {
            
                model.addRow(new Object[]{s.getStrTenBangDia(),s.getStrTenBaiHat(),s.getStrCaSi(),s.getStrNhacSi(),s.getStrNuocSX(),s.getIntNamSX()});
            }

        }
        if(radNuocSX.isSelected())
        {
            List<BangDiaThongTinBaiHat> listTT;
            String hoten=txtTim.getText();
            listTT=BangDiaThongTinBaiHatBL.timkiemTTBHtheoNuocSX(hoten);
              model =(DefaultTableModel)tblThongTinBD.getModel();
                model.setRowCount(0);
            if(listTT.size()<=0)
            {
              
                JOptionPane.showMessageDialog(rootPane,"Không tìm thấy nước sản xuất cần tìm !");
            }
            else
            for(BangDiaThongTinBaiHat s:listTT)
            {
                
                model.addRow(new Object[]{s.getStrTenBangDia(),s.getStrTenBaiHat(),s.getStrCaSi(),s.getStrNhacSi(),s.getStrNuocSX(),s.getIntNamSX()});
            }

        }
        if(radNamSX.isSelected())
        {
           List<BangDiaThongTinBaiHat> listTT;
            String hoten=txtTim.getText();
            listTT=BangDiaThongTinBaiHatBL.timkiemTTBHtheoNamSX(hoten);
            model =(DefaultTableModel)tblThongTinBD.getModel();
                model.setRowCount(0);
            if(listTT.size()<=0)
            {
                JOptionPane.showMessageDialog(rootPane,"Không tìm thấy năm sản xuất cần tìm !");
            }
            else
            for(BangDiaThongTinBaiHat s:listTT)
            {
                model.addRow(new Object[]{s.getStrTenBangDia(),s.getStrTenBaiHat(),s.getStrCaSi(),s.getStrNhacSi(),s.getStrNuocSX(),s.getIntNamSX()});
            }

        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        FrmMain mn=new FrmMain();
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed
DefaultTableModel model;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTimKiemThongTinBaiHat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTimKiemThongTinBaiHat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTimKiemThongTinBaiHat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTimKiemThongTinBaiHat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTimKiemThongTinBaiHat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.ButtonGroup btnChon;
    private javax.swing.JButton btnTim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radCaSi;
    private javax.swing.JRadioButton radNamSX;
    private javax.swing.JRadioButton radNhacSi;
    private javax.swing.JRadioButton radNuocSX;
    private javax.swing.JRadioButton radTenBD;
    private javax.swing.JRadioButton radTenBaiHat;
    private javax.swing.JTable tblThongTinBD;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
